# Generated by Django 3.2 on 2022-03-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jogo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('linha1', models.CharField(blank=True, max_length=20, null=True)),
                ('linha2', models.CharField(blank=True, max_length=20, null=True)),
                ('linha3', models.CharField(blank=True, max_length=20, null=True)),
                ('bolas_marcadas_linha1', models.CharField(blank=True, max_length=20, null=True)),
                ('bolas_marcadas_linha2', models.CharField(blank=True, max_length=20, null=True)),
                ('bolas_marcadas_linha3', models.CharField(blank=True, max_length=20, null=True)),
                ('vencedor_kuadra', models.BooleanField(default=False)),
                ('vencedor_kina', models.BooleanField(default=False)),
                ('vencedor_keno', models.BooleanField(default=False)),
                ('bolas_marcadas', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('comprado_em', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=30)),
                ('cancelado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_min_entre_sorteios', models.PositiveSmallIntegerField(default=1)),
                ('tempo_min_entre_sorteios_E', models.PositiveSmallIntegerField(default=30)),
                ('tempo_min_entre_sorteios_SE', models.PositiveSmallIntegerField(default=30)),
                ('iniciar_sorteio_em', models.PositiveSmallIntegerField(default=15)),
                ('logo_login', models.ImageField(blank=True, null=True, upload_to=jogo.models.configuracao_images_path)),
                ('logo_dash', models.ImageField(blank=True, null=True, upload_to=jogo.models.configuracao_images_path)),
                ('favicon', models.FileField(blank=True, null=True, upload_to=jogo.models.configuracao_images_path)),
                ('nome_server', models.CharField(blank=True, max_length=100, null=True)),
                ('token_server', models.CharField(blank=True, max_length=100, null=True)),
                ('edit_data_antecipar', models.BooleanField(default=False)),
                ('edit_data_adiar', models.BooleanField(default=False)),
                ('edit_horario_antecipar', models.BooleanField(default=False)),
                ('edit_horario_adiar', models.BooleanField(default=False)),
                ('edit_nome', models.BooleanField(default=False)),
                ('edit_kuadra', models.BooleanField(default=False)),
                ('edit_kina', models.BooleanField(default=False)),
                ('edit_keno', models.BooleanField(default=False)),
                ('cancelar_bilhete', models.BooleanField(default=False)),
                ('tempo_expirar_template', models.PositiveSmallIntegerField(default=2)),
                ('tempo_sorteio_online', models.PositiveSmallIntegerField(default=10)),
                ('imprimir_qrcode', models.BooleanField(default=False)),
                ('usar_ads', models.BooleanField(default=False)),
                ('usar_realtime', models.BooleanField(default=False)),
                ('quantidade_cartelas_compradas', models.PositiveIntegerField(default=1000)),
                ('pagamento_automatico', models.BooleanField(default=True)),
                ('versao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContadorCartelaPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('numeracao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DispositivosConectados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('nome_sala', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255, unique=True)),
                ('seguidores', models.BigIntegerField()),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('fone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=200, unique=True)),
                ('sessao_atual', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplatePartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_kuadra', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('valor_kina', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('valor_keno', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('data_partida', models.DateTimeField()),
                ('data_introducao', models.DateTimeField(auto_now_add=True)),
                ('play', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('id_automato', models.BigIntegerField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'APLICADO'), (1, 'CANCELADO')], null=True)),
                ('tipo_rodada', models.PositiveSmallIntegerField(choices=[(1, 'NORMAL'), (2, 'ESPECIAL'), (3, 'SUPER ESPECIAL')], default=1)),
                ('hora_virada', models.TimeField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_kuadra', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('valor_kina', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('valor_keno', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('tipo_rodada', models.PositiveSmallIntegerField(choices=[(1, 'NORMAL'), (2, 'ESPECIAL'), (3, 'SUPER ESPECIAL')], default=1)),
                ('data_partida', models.DateTimeField()),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('bolas_sorteadas', models.CharField(blank=True, max_length=255, null=True)),
                ('bola_kuadra', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bola_kina', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bola_keno', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_cartelas', models.IntegerField(default=0)),
                ('em_sorteio', models.BooleanField(default=False)),
                ('cartelas_participantes', models.TextField(blank=True, null=True)),
                ('sorteio', models.TextField(blank=True, null=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('nome_sorteio', models.CharField(blank=True, max_length=200, null=True)),
                ('partida_automatizada', models.BooleanField(default=False, null=True)),
                ('id_automato', models.BigIntegerField(blank=True, null=True)),
                ('premios_set', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cartelas_receberam_sorteio', models.ManyToManyField(blank=True, related_name='cartelas_receberam_sorteio', to='jogo.Cartela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogo.usuario')),
            ],
            options={
                'ordering': ['-data_partida'],
            },
        ),
        migrations.CreateModel(
            name='GrupoWebSocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jogo.partida')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.grupowebsocket')),
            ],
        ),
        migrations.CreateModel(
            name='CartelaVencedora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.PositiveSmallIntegerField(choices=[(1, 'KUADRA'), (2, 'KINA'), (3, 'KENO')])),
                ('linha_vencedora', models.SmallIntegerField(default=-1)),
                ('cartela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogo.cartela')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogo.partida')),
            ],
        ),
        migrations.AddField(
            model_name='cartela',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jogo.jogador'),
        ),
        migrations.AddField(
            model_name='cartela',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartelas', to='jogo.partida'),
        ),
        migrations.CreateModel(
            name='Automato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.PositiveSmallIntegerField()),
                ('quantidade_sorteios', models.PositiveSmallIntegerField()),
                ('tipo_rodada', models.PositiveSmallIntegerField(choices=[(1, 'NORMAL'), (2, 'ESPECIAL'), (3, 'SUPER ESPECIAL')], default=1)),
                ('partidas', models.ManyToManyField(blank=True, to='jogo.Partida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jogo.partida')),
            ],
        ),
        migrations.CreateModel(
            name='ADSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ativo'), (2, 'Pausa'), (3, 'Encerrado')], default=1)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.partida')),
            ],
        ),
    ]
